# Generated by Django 6.0.1 on 2026-02-02 01:00

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_name', models.CharField(max_length=3)),
                ('about_MD', models.TextField()),
                ('about_github', models.URLField()),
                ('about_doc', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('author_picture', models.ImageField(upload_to=portfolio.models.author_image_path)),
                ('author_description', models.ImageField(max_length=200, upload_to='')),
                ('author_biography', models.TextField()),
                ('author_mail', models.EmailField(max_length=254)),
                ('author_github', models.URLField()),
                ('author_linkedin', models.URLField()),
                ('contact_MD', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_picture', models.ImageField(upload_to=portfolio.models.project_image_path)),
                ('project_github', models.URLField()),
                ('project_link', models.URLField(blank=True)),
                ('project_description', models.TextField()),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology')),
            ],
        ),
    ]
