# Generated by Django 6.0.1 on 2026-01-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bio',
            new_name='Author',
        ),
    ]
